# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Process `dosearch` Calls from R
#'
#' @param dir_lhs A vector of vertices with outgoing directed edges
#' @param dir_rhs A vector of vertices with incoming directed edges
#' @param bi_lhs A vector of vertices with incoming bidirected edges
#' @param bi_rhs A vector of vertices with incoming bidirected edges
#' @param lab A vector of labels for vertices
#' @param p_list A list of known distributions
#' @param q_vec A vector of vertices representing the causal query
#' @param n The number of vertices
#' @param tr A set representing transportability nodes
#' @param sb A set representing selection bias nodes
#' @param md_s A set representing missing data switches
#' @param md_p A set representing missing data proxies
#' @param path_rules Rules to use for every input distribution in validation
#' @param time_limit Time limit for the search (in hours)
#' @param rules Overrides the set of default rules
#' @param benchmark Record the search time
#' @param benchmark_rules Record time taken by each individual rule
#' @param draw_derivation Form a string representing the
#'   derivation steps (as dot)
#' @param draw_all Draw every distribution that was derived
#'   (vs only those that were used to derive the effect)
#' @param formula Output formula as string
#' @param improve Enable search enhancements
#' @param heuristic Use search heuristic
#' @param md_sym Symbol used to represent active missing data mechanisms
#' @param verbose Print diagnostics during search
#' @param validate_run Parameter for developing dosearch validation
#' @noRd
initialize_dovalidate <- function(dir_lhs, dir_rhs, bi_lhs, bi_rhs, lab, p_list, q_vec, n, tr, sb, md_s, md_p, path_rules, time_limit, rules, benchmark, benchmark_rules, draw_derivation, draw_all, formula, improve, heuristic, md_sym, verbose, validate_run) {
    .Call(`_dovalidate_initialize_dovalidate`, dir_lhs, dir_rhs, bi_lhs, bi_rhs, lab, p_list, q_vec, n, tr, sb, md_s, md_p, path_rules, time_limit, rules, benchmark, benchmark_rules, draw_derivation, draw_all, formula, improve, heuristic, md_sym, verbose, validate_run)
}

